import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FFF9FC",
  },
  hydrationWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  hydrationText: {
    color: "#5E5264",
    fontSize: 16,
    fontWeight: "600",
  },
  decorLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  decorIcon: {
    position: "absolute",
    opacity: 0.45,
  },
  bubble: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#FFFFFF",
    opacity: 0.64,
  },
  onboardingWrapper: {
    flex: 1,
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 18,
  },
  progressText: {
    textAlign: "center",
    color: "#7A707D",
    fontSize: 14,
    marginBottom: 10,
    fontWeight: "600",
  },
  onboardingStageWelcome: {
    flex: 1,
  },
  onboardingStageCard: {
    flex: 1,
  },
  welcomeStage: {
    flex: 1,
    justifyContent: "center",
  },
  welcomeIllustration: {
    alignItems: "center",
    justifyContent: "center",
    height: "55%",
    marginBottom: 10,
  },
  onboardingImage: {
    width: "100%",
    height: "100%",
  },
  welcomeTextBlock: {
    alignItems: "center",
    marginTop: 8,
    gap: 10,
  },
  welcomeTitle: {
    fontSize: 46,
    lineHeight: 56,
    fontWeight: "700",
    color: "#0E0D15",
    textAlign: "center",
  },
  welcomeSubtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: "#7D707C",
    textAlign: "center",
    fontWeight: "500",
  },
  card: {
    flex: 1,
    backgroundColor: "#FFFFFFF2",
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderWidth: 1,
    borderColor: "#EEE2EA",
  },
  contentBlock: {
    flex: 1,
  },
  title: {
    fontSize: 31,
    color: "#1A1521",
    lineHeight: 40,
    fontWeight: "700",
  },
  descriptionLeft: {
    marginTop: 10,
    color: "#7D707C",
    fontSize: 16,
    lineHeight: 24,
  },
  descriptionMuted: {
    marginTop: 6,
    color: "#8F8092",
    fontSize: 14,
  },
  input: {
    marginTop: 22,
    borderWidth: 1,
    borderColor: "#DED0DD",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 17,
    color: "#332A37",
    backgroundColor: "#FFFFFF",
  },
  optionList: {
    marginTop: 18,
    gap: 12,
  },
  optionButton: {
    borderWidth: 1,
    borderColor: "#D8C9D8",
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 16,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  optionButtonActive: {
    borderColor: "#9678CA",
    backgroundColor: "#F6EEFC",
  },
  optionText: {
    fontSize: 17,
    color: "#4A4050",
    fontWeight: "500",
  },
  optionTextActive: {
    color: "#674A9D",
    fontWeight: "700",
  },
  optionIndicator: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#C9B8D0",
    alignItems: "center",
    justifyContent: "center",
  },
  optionIndicatorActive: {
    borderColor: "#9678CA",
    backgroundColor: "#9678CA",
  },
  monthHeader: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  monthArrow: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DFD0DE",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  monthArrowText: {
    fontSize: 18,
    color: "#4A4050",
    fontWeight: "700",
  },
  monthTitle: {
    fontSize: 17,
    color: "#4A4050",
    fontWeight: "700",
  },
  weekHeader: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 4,
  },
  weekDayText: {
    width: "14.28%",
    textAlign: "center",
    color: "#8B7E8D",
    fontWeight: "600",
    fontSize: 12,
  },
  calendarGrid: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  dayCell: {
    width: "14.28%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginBottom: 2,
  },
  dayCellMuted: {
    opacity: 0.35,
  },
  dayCellSelected: {
    backgroundColor: "#E7D8F8",
  },
  dayCellText: {
    color: "#54485A",
    fontSize: 15,
    fontWeight: "500",
  },
  dayCellTextMuted: {
    color: "#8E8190",
  },
  dayCellTextSelected: {
    color: "#4C3A70",
    fontWeight: "700",
  },
  dayPeriod: {
    backgroundColor: "#D8C3F9",
  },
  dayOvulation: {
    backgroundColor: "#BFDDFE",
  },
  dayFertility: {
    backgroundColor: "#CDEFD9",
  },
  selectedCalendarDayOutline: {
    borderWidth: 2,
    borderColor: "#6A5A88",
  },
  todayOutline: {
    borderWidth: 1,
    borderColor: "#6E5B79",
  },
  calendarHintText: {
    marginTop: 10,
    color: "#7B6E80",
    fontSize: 13,
    textAlign: "center",
    marginBottom: 12,
  },
  periodStartButton: {
    backgroundColor: "#8F72C5",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 12,
    shadowColor: "#8F72C5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  periodStartButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  setAsPeriodButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FDF8FD",
    marginTop: 4,
  },
  setAsPeriodButtonText: {
    color: "#8F72C5",
    fontSize: 14,
    fontWeight: "700",
  },
  probabilityCard: {
    marginTop: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFFF2",
    padding: 12,
    gap: 6,
  },
  probabilityHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  probabilityTitle: {
    color: "#2D2433",
    fontSize: 16,
    fontWeight: "800",
  },
  probabilityDateLabel: {
    color: "#8B7D8E",
    fontSize: 12,
    marginTop: 2,
    fontWeight: "600",
  },
  probabilityBadge: {
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  probabilityBadgeHigh: {
    backgroundColor: "#FCDDE6",
  },
  probabilityBadgeMedium: {
    backgroundColor: "#FDF1D9",
  },
  probabilityBadgeLow: {
    backgroundColor: "#E9EFF9",
  },
  probabilityBadgeText: {
    color: "#4A3F53",
    fontSize: 11,
    fontWeight: "800",
  },
  probabilitySummary: {
    color: "#4C3F53",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  probabilityMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  probabilityMetaText: {
    color: "#7B6F7E",
    fontSize: 12,
    fontWeight: "700",
  },
  probabilityWindowText: {
    color: "#6E6172",
    fontSize: 12,
    lineHeight: 17,
  },
  probabilityRecommendation: {
    color: "#5A4E60",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  confirmedDateText: {
    marginTop: 14,
    textAlign: "center",
    color: "#574B5C",
    fontSize: 15,
    fontWeight: "600",
  },
  adjusterWrap: {
    marginTop: 18,
    borderWidth: 1,
    borderColor: "#E1D4E3",
    borderRadius: 18,
    padding: 14,
    backgroundColor: "#FFFFFF",
    gap: 10,
  },
  adjusterTextWrap: {
    gap: 4,
  },
  adjusterLabel: {
    fontSize: 16,
    color: "#302636",
    fontWeight: "700",
  },
  adjusterHint: {
    fontSize: 13,
    color: "#8A7C8E",
  },
  adjusterControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  adjustButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#CDBAD1",
    alignItems: "center",
    justifyContent: "center",
  },
  adjustButtonDisabled: {
    opacity: 0.45,
  },
  adjustButtonText: {
    color: "#594D61",
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "600",
  },
  adjustValue: {
    fontSize: 20,
    color: "#322739",
    fontWeight: "700",
    minWidth: 44,
    textAlign: "center",
  },
  reminderRow: {
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#E1D4E3",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerButtons: {
    marginTop: 14,
    flexDirection: "row",
    gap: 10,
  },
  footerButtonsSingle: {
    marginTop: 8,
  },
  secondaryButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#D8C9D8",
    backgroundColor: "#FFFFFFE6",
    minHeight: 56,
  },
  secondaryButtonText: {
    color: "#4A4050",
    fontSize: 16,
    fontWeight: "600",
  },
  primaryButton: {
    flex: 2,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 28,
    minHeight: 56,
    backgroundColor: "#8F72C5",
  },
  primaryButtonDisabled: {
    backgroundColor: "#C7B4E4",
  },
  primaryButtonFull: {
    flex: 1,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  postOnboardingWrapper: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 12,
  },
  tabContent: {
    flex: 1,
  },
  tabScrollContent: {
    paddingTop: 8,
    paddingBottom: 24,
    gap: 12,
  },
  homeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 29,
    color: "#17111E",
    fontWeight: "800",
  },
  headerSubtitle: {
    color: "#7F7183",
    marginTop: 4,
    fontSize: 14,
  },
  profileAvatarWrap: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#8F72C5",
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  homeProBadge: {
    borderRadius: 10,
    backgroundColor: "#F7B84B",
    borderWidth: 1,
    borderColor: "#FFFFFF",
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  homeProBadgeWrap: {
    position: "absolute",
    bottom: -4,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  homeProBadgeText: {
    color: "#4F3A09",
    fontSize: 10,
    fontWeight: "800",
  },
  insightRow: {
    paddingHorizontal: 18,
    gap: 12,
    paddingVertical: 4,
  },
  insightCard: {
    width: 200,
    borderRadius: 24,
    padding: 16,
    gap: 10,
  },
  insightCardTop: {
    flexDirection: "row",
    alignItems: "center",
  },
  insightIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  insightCardBody: {
    gap: 2,
  },
  insightHeroValue: {
    fontSize: 36,
    fontWeight: "900",
    lineHeight: 40,
  },
  insightHeroLabel: {
    fontSize: 14,
    color: "#4A4050",
    fontWeight: "600",
    lineHeight: 19,
  },
  insightSubtitle: {
    fontSize: 12,
    color: "#8A7C8D",
    lineHeight: 17,
    fontWeight: "500",
  },
  monthChipRow: {
    paddingTop: 14,
    paddingBottom: 4,
    gap: 8,
  },
  monthChip: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#DFD0DE",
    backgroundColor: "#FFFFFF",
  },
  monthChipActive: {
    borderColor: "#8F72C5",
    backgroundColor: "#EFE4FB",
  },
  monthChipText: {
    color: "#645869",
    fontWeight: "600",
    fontSize: 13,
  },
  monthChipTextActive: {
    color: "#674A9D",
  },
  calendarCard: {
    marginTop: 4,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFFF2",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  calendarCardTitle: {
    fontSize: 17,
    color: "#302636",
    fontWeight: "700",
    textAlign: "center",
  },
  legendRow: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendText: {
    color: "#7E7081",
    fontSize: 12,
    fontWeight: "600",
  },
  insightSectionTitle: {
    color: "#2C2232",
    fontSize: 26,
    fontWeight: "800",
    marginTop: 4,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  statCard: {
    width: "48.5%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E6D8E8",
    padding: 14,
    gap: 6,
  },
  statCardPink: {
    backgroundColor: "#FCEEF4",
  },
  statCardLavender: {
    backgroundColor: "#F7F0FC",
  },
  statCardPeach: {
    backgroundColor: "#FFF3EA",
  },
  statCardMint: {
    backgroundColor: "#ECF8F1",
  },
  statTitle: {
    color: "#6D6171",
    fontSize: 14,
    fontWeight: "600",
  },
  statValue: {
    color: "#2E2435",
    fontSize: 32,
    lineHeight: 36,
    fontWeight: "800",
  },
  statSubtext: {
    color: "#8A7C8D",
    fontSize: 13,
    lineHeight: 18,
  },
  overviewCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFFEE",
    padding: 16,
    gap: 16,
  },
  overviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  overviewTitle: {
    color: "#2F2436",
    fontSize: 22,
    fontWeight: "800",
  },
  overviewBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F0E8FA",
    alignItems: "center",
    justifyContent: "center",
  },
  cycleOverviewScroll: {
    paddingHorizontal: 4,
    gap: 12,
  },
  cycleMonthCard: {
    width: 180,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFF",
    padding: 14,
    gap: 12,
  },
  cycleMonthCardActive: {
    borderColor: "#8F72C5",
    backgroundColor: "#F7F2FF",
  },
  cycleMonthHeader: {
    alignItems: "center",
    gap: 2,
  },
  cycleMonthLabel: {
    color: "#6B5F70",
    fontSize: 15,
    fontWeight: "700",
  },
  cycleMonthLabelActive: {
    color: "#8F72C5",
  },
  cycleMonthYear: {
    color: "#9A8B9C",
    fontSize: 12,
    fontWeight: "600",
  },
  cycleMonthYearActive: {
    color: "#8F72C5",
  },
  cycleStatsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 8,
  },
  cycleStatItem: {
    alignItems: "center",
    gap: 4,
  },
  cycleStatIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  cycleStatValue: {
    color: "#4A4050",
    fontSize: 18,
    fontWeight: "800",
  },
  cycleStatValueActive: {
    color: "#8F72C5",
  },
  cycleStatLabel: {
    color: "#8A7C8D",
    fontSize: 10,
    fontWeight: "600",
  },
  cycleMiniChart: {
    gap: 6,
  },
  cycleMiniBarTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F0E8F2",
    flexDirection: "row",
    overflow: "hidden",
  },
  cycleMiniBar: {
    height: 8,
  },
  cycleMiniChartLabel: {
    color: "#7A6D7F",
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },
  cycleSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#F7F2FF",
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  cycleSummaryItem: {
    alignItems: "center",
    gap: 4,
  },
  cycleSummaryValue: {
    color: "#8F72C5",
    fontSize: 20,
    fontWeight: "800",
  },
  cycleSummaryLabel: {
    color: "#7A6D7F",
    fontSize: 11,
    fontWeight: "600",
  },
  cycleSummaryDivider: {
    width: 1,
    height: 32,
    backgroundColor: "#E7DCE6",
  },
  proInsightsCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E6D9EA",
    backgroundColor: "#FFFDFE",
    padding: 14,
    gap: 6,
    marginTop: 2,
  },
  proInsightsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  proInsightsTitle: {
    color: "#2F2436",
    fontSize: 16,
    fontWeight: "700",
  },
  proInsightsText: {
    color: "#5C4F64",
    fontSize: 13,
    lineHeight: 18,
  },
  proInsightsLockedText: {
    color: "#7A6D7F",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  proInsightsUnlockButton: {
    alignSelf: "flex-start",
    borderRadius: 16,
    backgroundColor: "#8F72C5",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  proInsightsUnlockText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  aiPageWrap: {
    flex: 1,
    gap: 10,
  },
  aiHeroCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E6D9E9",
    padding: 16,
    gap: 12,
  },
  aiHeroTitle: {
    color: "#2F2436",
    fontSize: 24,
    fontWeight: "800",
  },
  aiHeroSubtitle: {
    marginTop: 6,
    color: "#7C6F80",
    fontSize: 14,
    lineHeight: 20,
  },
  aiStatusChip: {
    alignSelf: "flex-start",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D9CBE7",
    backgroundColor: "#F4EEFB",
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  aiStatusChipText: {
    color: "#5D4193",
    fontSize: 12,
    fontWeight: "700",
  },
  aiQuotaCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E1D4E5",
    backgroundColor: "#FFFFFFF0",
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  aiQuotaTitle: {
    color: "#55495D",
    fontSize: 12,
    fontWeight: "600",
  },
  aiQuotaUpgradeText: {
    color: "#7F5DBE",
    fontSize: 12,
    fontWeight: "700",
  },
  aiPromptRow: {
    gap: 8,
    paddingRight: 4,
    alignItems: "center",
  },
  aiPromptScroll: {
    flexGrow: 0,
  },
  aiPromptChip: {
    alignSelf: "flex-start",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DDCFE3",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  aiPromptChipText: {
    color: "#5E5264",
    fontSize: 13,
    fontWeight: "600",
  },
  aiMessagesScroll: {
    flex: 1,
  },
  aiMessagesContent: {
    gap: 8,
    paddingBottom: 8,
  },
  aiBubble: {
    maxWidth: "86%",
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  aiAssistantBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFFEC",
    borderWidth: 1,
    borderColor: "#E7DCE6",
  },
  aiUserBubble: {
    alignSelf: "flex-end",
    backgroundColor: "#8F72C5",
  },
  aiBubbleText: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: undefined,
  },
  aiAssistantBubbleText: {
    color: "#3A2E40",
    fontSize: 14,
    lineHeight: 20,
  },
  aiUserBubbleText: {
    color: "#FFFFFF",
  },
  aiTypingBubble: {
    opacity: 0.8,
  },
  aiComposerWrap: {
    marginTop: 2,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E3D6E7",
    backgroundColor: "#FFFFFFF0",
    padding: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  aiInput: {
    flex: 1,
    minHeight: 40,
    color: "#2F2436",
    fontSize: 15,
    paddingHorizontal: 8,
  },
  aiSendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#8F72C5",
    alignItems: "center",
    justifyContent: "center",
  },
  aiSendButtonDisabled: {
    backgroundColor: "#C2AFDD",
  },
  settingsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  settingsBackButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2D6E5",
    backgroundColor: "#FFFFFFEE",
    alignItems: "center",
    justifyContent: "center",
  },
  settingsHeaderTitle: {
    fontSize: 24,
    color: "#2F2436",
    fontWeight: "800",
  },
  settingsHeaderSpacer: {
    width: 36,
  },
  settingsCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFFEE",
    padding: 14,
    gap: 10,
  },
  settingsSectionTitle: {
    color: "#3A2F40",
    fontSize: 16,
    fontWeight: "800",
  },
  settingsSwitchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  settingsSwitchTextWrap: {
    flex: 1,
    gap: 3,
  },
  settingsRowTitle: {
    color: "#3F3346",
    fontSize: 15,
    fontWeight: "700",
  },
  settingsRowSubtitle: {
    color: "#817486",
    fontSize: 12,
    lineHeight: 17,
  },
  settingsNavRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#F0E8F2",
    paddingTop: 10,
  },
  settingsNavRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  settingsNavValue: {
    color: "#8B7D8F",
    fontSize: 13,
    fontWeight: "600",
  },
  editProfileAvatarWrap: {
    paddingTop: 6,
    alignItems: "center",
  },
  editProfileFieldLabel: {
    color: "#4C3D54",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 6,
  },
  editProfileInput: {
    borderWidth: 1,
    borderColor: "#DED0DD",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: "#332A37",
    backgroundColor: "#FFFFFF",
  },
  editProfileActionsRow: {
    marginTop: 4,
    flexDirection: "row",
    gap: 10,
  },
  editProfileCancelButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D8CADE",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  editProfileCancelButtonText: {
    color: "#6C5F73",
    fontSize: 14,
    fontWeight: "700",
  },
  editProfileSaveButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8F72C5",
  },
  editProfileSaveButtonDisabled: {
    backgroundColor: "#C5B3DE",
  },
  editProfileSaveButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  profileHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  profileIdentityWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profileAvatarLarge: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#8F72C5",
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarLargeText: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
  },
  profileName: {
    color: "#2C2232",
    fontSize: 24,
    fontWeight: "800",
  },
  profileMetaText: {
    color: "#7D6F81",
    fontSize: 13,
    marginTop: 2,
  },
  profilePlanText: {
    color: "#7E63B2",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
  },
  profileSettingsIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2D6E5",
    backgroundColor: "#FFFFFFEE",
    alignItems: "center",
    justifyContent: "center",
  },
  profileHeroCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E8DCEC",
    backgroundColor: "#F7EEF9",
    padding: 14,
    gap: 6,
  },
  profileHeroTitle: {
    color: "#2F2436",
    fontSize: 18,
    fontWeight: "800",
  },
  profileHeroSubtitle: {
    color: "#7C6F80",
    fontSize: 13,
    lineHeight: 19,
  },
  profileStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  profileStatCard: {
    width: "48.5%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    padding: 12,
    gap: 5,
  },
  profileStatCardLavender: {
    backgroundColor: "#F5EEFB",
  },
  profileStatCardPink: {
    backgroundColor: "#FDF0F5",
  },
  profileStatCardMint: {
    backgroundColor: "#EDF8F2",
  },
  profileStatCardPeach: {
    backgroundColor: "#FFF4EB",
  },
  profileStatTitle: {
    color: "#726575",
    fontSize: 13,
    fontWeight: "600",
  },
  profileStatValue: {
    color: "#2F2436",
    fontSize: 27,
    lineHeight: 32,
    fontWeight: "800",
  },
  profileStatValueSmall: {
    color: "#2F2436",
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
  },
  profileMenuCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFFEE",
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  profileMenuRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#F0E7F2",
  },
  profileMenuLabelWrap: {
    flex: 1,
    gap: 2,
    paddingRight: 10,
  },
  profileMenuTitle: {
    color: "#3E3345",
    fontSize: 15,
    fontWeight: "700",
  },
  profileMenuSubtitle: {
    color: "#8A7D8E",
    fontSize: 12,
  },
  tipsQuestion: {
    color: "#2F2436",
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "700",
  },
  flowCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E4D5E9",
    backgroundColor: "#F5E6F4",
    padding: 12,
    gap: 10,
    marginBottom: 8,
  },
  flowCardTitle: {
    color: "#2F2436",
    fontSize: 18,
    fontWeight: "700",
  },
  flowTabRow: {
    flexDirection: "row",
    gap: 8,
  },
  flowTab: {
    flex: 1,
    minHeight: 42,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E5D8E8",
    backgroundColor: "#FAF2FB",
    paddingHorizontal: 8,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  flowTabActive: {
    borderColor: "#8F72C5",
    backgroundColor: "#8F72C5",
  },
  flowDropRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  flowLabel: {
    color: "#44384D",
    fontSize: 12,
    fontWeight: "600",
  },
  flowLabelActive: {
    color: "#FFFFFF",
  },
  moodGrid: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  saveCheckinButton: {
    marginTop: 12,
    alignSelf: "flex-start",
    borderRadius: 18,
    backgroundColor: "#8F72C5",
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  saveCheckinButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  todayCheckInBanner: {
    backgroundColor: "#E8F5E9",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4CAF50",
    padding: 12,
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  todayCheckInBannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  todayCheckInBannerText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2E7D32",
  },
  todayCheckInBannerLink: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1976D2",
    textDecorationLine: "underline",
  },
  viewHistoryButton: {
    marginTop: 8,
    alignSelf: "flex-start",
    borderRadius: 18,
    backgroundColor: "#F0E8FA",
    borderWidth: 1,
    borderColor: "#8F72C5",
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  viewHistoryButtonText: {
    color: "#8F72C5",
    fontSize: 13,
    fontWeight: "700",
  },
  historyModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
    paddingHorizontal: 12,
    paddingBottom: 10,
  },
  historyModalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    maxHeight: "85%",
    minHeight: "55%",
    overflow: "hidden",
  },
  historyModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  historyModalTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#2F2436",
  },
  historyList: {
    flex: 1,
    minHeight: 140,
  },
  historyListContent: {
    gap: 14,
    paddingBottom: 8,
    flexGrow: 1,
  },
  historyEntryListContainer: {
    gap: 10,
  },
  historyEntryItem: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E6DDEE",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  historyEntryItemActive: {
    borderColor: "#8F72C5",
    backgroundColor: "#F7F2FF",
  },
  historyEntryTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  historyEntryDateText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#4D4157",
  },
  historyEntryDateTextActive: {
    color: "#5D4193",
  },
  historyEntryTodayBadge: {
    backgroundColor: "#E9DFFF",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  historyEntryTodayBadgeText: {
    color: "#6A4CA5",
    fontSize: 10,
    fontWeight: "700",
  },
  historyEntryMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  historyEntryFlowText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#715D86",
  },
  historyEntryMoodText: {
    flex: 1,
    fontSize: 12,
    color: "#6C5E74",
  },
  historyDetailsWrap: {
    marginTop: 6,
    gap: 10,
  },
  historyDetailsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#4D4157",
  },
  emptyHistoryContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyHistoryText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#5E5265",
    marginTop: 16,
  },
  historyCard: {
    backgroundColor: "#FEFBFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E1D4E2",
    padding: 16,
    marginBottom: 12,
  },
  historyCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  historyDateContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  todayBadge: {
    backgroundColor: "#8F72C5",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  todayBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "700",
  },
  historyFlowRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    justifyContent: "space-between",
  },
  historyFlowText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#8F72C5",
    marginLeft: 4,
  },
  historyMoodsContainer: {
    marginTop: 8,
  },
  historyMoodsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  historyMoodChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0E8FA",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
  },
  historyMoodEmoji: {
    fontSize: 14,
  },
  historyMoodLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#5D4193",
  },
  historyCloseButton: {
    backgroundColor: "#8F72C5",
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 16,
  },
  historyCloseButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  historyModalGradient: {
    flex: 1,
    paddingTop: 24,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  historyModalHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  historyModalIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#F0E8FA",
    alignItems: "center",
    justifyContent: "center",
  },
  historyModalSubtitle: {
    fontSize: 13,
    color: "#7D6F81",
    marginTop: 2,
  },
  historyModalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F5F0FA",
    alignItems: "center",
    justifyContent: "center",
  },
  historyListEmptyCenter: {
    flexGrow: 1,
    justifyContent: "center",
  },
  emptyHistoryIconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  emptyHistoryTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#2F2436",
    marginBottom: 8,
  },
  emptyHistoryButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#8F72C5",
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 8,
    marginTop: 20,
    shadowColor: "#8F72C5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 3,
  },
  emptyHistoryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  historyDateBadge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#8F72C5",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  historyDateBadgeToday: {
    shadowColor: "#8F72C5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  historyDateDay: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  historyDateMonth: {
    fontSize: 11,
    fontWeight: "700",
    color: "#FFFFFF",
    textTransform: "uppercase",
  },
  historyDeleteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFEBEE",
    alignItems: "center",
    justifyContent: "center",
  },
  historyCardBody: {
    gap: 12,
  },
  historyFlowIconContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  historyFlowLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#5E5265",
  },
  historyFlowValueContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  historyFlowDrop: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#F0E8FA",
    alignItems: "center",
    justifyContent: "center",
  },
  historyMoodsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  historyMoodsLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#5E5265",
  },
  moodChip: {
    minWidth: "31%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E1D4E2",
    backgroundColor: "#FEFBFF",
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  moodChipActive: {
    borderColor: "#8F72C5",
    backgroundColor: "#F0E8FA",
  },
  moodEmoji: {
    fontSize: 21,
  },
  moodLabel: {
    color: "#5E5265",
    fontSize: 12,
    fontWeight: "600",
  },
  moodLabelActive: {
    color: "#5D4193",
  },
  tipsSectionWrap: {
    gap: 10,
  },
  tipsSectionTitle: {
    color: "#2F2436",
    fontSize: 19,
    fontWeight: "700",
  },
  tipsCarouselRow: {
    gap: 10,
    paddingRight: 6,
  },
  tipCard: {
    width: 250,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5D8E7",
    backgroundColor: "#FFFFFFEE",
    padding: 14,
    gap: 8,
  },
  tipTitle: {
    color: "#362C3D",
    fontSize: 17,
    fontWeight: "700",
  },
  tipDetail: {
    color: "#76697D",
    fontSize: 14,
    lineHeight: 20,
  },
  tipsSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  tipsSectionBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F0E8FA",
    alignItems: "center",
    justifyContent: "center",
  },
  tipsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  tipsGridScroll: {
    paddingHorizontal: 4,
    gap: 12,
  },
  tipCardNew: {
    width: 155,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFF",
    padding: 12,
    gap: 10,
  },
  tipCardLeft: {
    width: "100%",
  },
  tipIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  tipContent: {
    flex: 1,
    gap: 4,
  },
  tipTitleNew: {
    color: "#2F2436",
    fontSize: 16,
    fontWeight: "700",
  },
  tipDetailNew: {
    color: "#7A6D7F",
    fontSize: 13,
    lineHeight: 18,
  },
  tipArrow: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#F0E8FA",
    alignItems: "center",
    justifyContent: "center",
  },
  tipsMoreButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8F72C5",
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginTop: 8,
    gap: 8,
  },
  tipsMoreButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  breathingContainer: {
    borderRadius: 32,
    borderWidth: 1,
    borderColor: "#EBE0FF",
    padding: 24,
    gap: 20,
    shadowColor: "#8F72C5",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 4,
    overflow: "hidden",
  },
  breathingHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  breathingTitle: {
    fontSize: 22,
    color: "#2F2436",
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  breathingSubtitle: {
    fontSize: 14,
    color: "#8F72C5",
    fontWeight: "600",
    marginTop: 2,
  },
  breathingVisualArea: {
    height: 220,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  breathingCircleBackground: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  breathingRipple1: {
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#E9DFFF",
    opacity: 0.5,
    position: "absolute",
  },
  breathingRipple2: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 1,
    borderColor: "#E9DFFF",
    opacity: 0.8,
    position: "absolute",
  },
  breathingMainCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    shadowColor: "#8F72C5",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  breathingCircleGradient: {
    flex: 1,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  breathingPhaseOverlay: {
    position: "absolute",
    bottom: -10,
    alignItems: "center",
  },
  breathingPhaseText: {
    fontSize: 18,
    color: "#4A3F53",
    fontWeight: "800",
    textAlign: "center",
  },
  breathingTimerText: {
    fontSize: 14,
    color: "#8F72C5",
    fontWeight: "700",
    marginTop: 4,
  },
  breathingDescription: {
    fontSize: 15,
    color: "#7B6E80",
    textAlign: "center",
    lineHeight: 22,
    paddingHorizontal: 10,
  },
  breathingStartButton: {
    backgroundColor: "#8F72C5",
    borderRadius: 20,
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#8F72C5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  breathingStopButton: {
    backgroundColor: "#2F2436",
    shadowColor: "#000000",
  },
  breathingStartButtonText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "700",
  },
  sectionTitle: {
    fontSize: 28,
    color: "#17111E",
    fontWeight: "800",
    marginBottom: 4,
  },
  infoCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFFEE",
    padding: 16,
    gap: 6,
  },
  infoLabel: {
    color: "#8A7C8D",
    fontSize: 14,
    fontWeight: "600",
  },
  infoValue: {
    color: "#392E40",
    fontSize: 19,
    fontWeight: "700",
  },
  infoFootnote: {
    color: "#7B6E80",
    fontSize: 13,
  },
  reminderSettingCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E7DCE6",
    backgroundColor: "#FFFFFFEE",
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bottomNavBar: {
    marginTop: 8,
    borderRadius: 24,
    backgroundColor: "#FFFFFFF0",
    borderWidth: 1,
    borderColor: "#E4D8E8",
    paddingHorizontal: 8,
    paddingVertical: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  navIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  navIconWrapActive: {
    backgroundColor: "#8F72C5",
  },
  navText: {
    fontSize: 12,
    color: "#6E6074",
    fontWeight: "600",
  },
  navTextActive: {
    color: "#614694",
    fontWeight: "700",
  },
  proSuccessOverlay: {
    flex: 1,
    backgroundColor: "rgba(18, 10, 26, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  proSuccessCard: {
    width: "100%",
    maxWidth: 340,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8DDEB",
    paddingHorizontal: 20,
    paddingVertical: 24,
    alignItems: "center",
    gap: 10,
  },
  proSuccessIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#8F72C5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  proSuccessTitle: {
    color: "#2F2436",
    fontSize: 24,
    fontWeight: "800",
    textAlign: "center",
  },
  proSuccessText: {
    color: "#64576B",
    fontSize: 15,
    lineHeight: 21,
    textAlign: "center",
  },
  proSuccessButton: {
    marginTop: 6,
    width: "100%",
    borderRadius: 16,
    backgroundColor: "#8F72C5",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  proSuccessButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  languageModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  languageModalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 24,
    width: "80%",
    maxWidth: 320,
  },
  languageModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#4B3E53",
    marginBottom: 16,
    textAlign: "center",
  },
  languageOptionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F0EAF4",
  },
  languageOptionText: {
    fontSize: 16,
    color: "#4B3E53",
  },
  languageOptionTextActive: {
    color: "#8F72C5",
    fontWeight: "700",
  },
  languageCancelButton: {
    marginTop: 16,
    alignItems: "center",
    paddingVertical: 10,
  },
  languageCancelText: {
    fontSize: 15,
    color: "#85788A",
    fontWeight: "600",
  },
  subscriptionModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  subscriptionModalCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    padding: 18,
    gap: 10,
  },
  subscriptionModalTitle: {
    color: "#2F2436",
    fontSize: 20,
    fontWeight: "800",
  },
  subscriptionModalSubtitle: {
    color: "#7D6F81",
    fontSize: 13,
    marginBottom: 4,
  },
  subscriptionPlanButton: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5D9E8",
    backgroundColor: "#FAF7FC",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subscriptionPlanButtonDisabled: {
    opacity: 0.5,
  },
  subscriptionPlanTitle: {
    color: "#3F3346",
    fontSize: 14,
    fontWeight: "700",
  },
  subscriptionPlanPrice: {
    color: "#877A8A",
    fontSize: 12,
    marginTop: 2,
  },
  subscriptionActionButton: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DED1E3",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  subscriptionActionButtonText: {
    color: "#5D4193",
    fontSize: 13,
    fontWeight: "700",
  },
  subscriptionCloseButton: {
    marginTop: 4,
    borderRadius: 14,
    backgroundColor: "#8F72C5",
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  subscriptionCloseButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
});
